#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Lite-FTP
version:      0.21
version_from: VERSION
licence: perl
installdirs:  site
copyright: perl
requires:
    Net::SSLeay::Handle:                     0.0

distribution_type: module
generated_by: Eyck v1.00
